### ISSUE TITLE
Can't open the clickhouse example

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/vdibis#33]
hi! I installed a conda env with python 3.8
I installed vdsql with `pip install git+https://github.com/visidata/vdsql.git`

I opened `vdsql clickhouse://explorer@play.clickhouse.com:9440/?secure=1`. It connects successfully.

When I open any table (including `recipies`) I get an error `DB::ParsingException. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '1'. Stack trace:`

I'm on an M1 mac with the currently latest macos 13.4.1

What might be wrong?

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/visidata/sheets.py", line 290, in reload
    for r in self.iterload():
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/vdsql/clickhouse.py", line 39, in iterload
    for row in self.query_result:
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/clickhouse_driver/util/helpers.py", line 16, in chunks
    item = list(islice(it, n))
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/clickhouse_driver/client.py", line 213, in iter_receive_result
    for rows in result:
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/clickhouse_driver/result.py", line 114, in __next__
    packet = next(self.packet_generator)
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/clickhouse_driver/client.py", line 220, in packet_generator
    packet = self.receive_packet()
  File "/Users/user/miniconda3/envs/p308/lib/python3.8/site-packages/clickhouse_driver/client.py", line 237, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 26.
DB::ParsingException. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '1'. Stack trace:

0. ./build_docker/./src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e32b635 in /usr/bin/clickhouse
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::ParsingException::ParsingException<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000e3914fd in /usr/bin/clickhouse
2. ./build_docker/./src/IO/ReadHelpers.cpp:0: void DB::readQuotedStringInto<false, String>(String&, DB::ReadBuffer&) @ 0x000000000e380760 in /usr/bin/clickhouse
3. ./build_docker/./src/Core/BaseSettings.h:820: DB::TCPHandler::receiveQuery() @ 0x0000000014c77de0 in /usr/bin/clickhouse
4. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::receivePacket() @ 0x0000000014c6e32e in /usr/bin/clickhouse
5. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x0000000014c65750 in /usr/bin/clickhouse
6. ./build_docker/./src/Server/TCPHandler.cpp:2045: DB::TCPHandler::run() @ 0x0000000014c7bbb9 in /usr/bin/clickhouse
7. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000017bc3c54 in /usr/bin/clickhouse
8. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x0000000017bc4e71 in /usr/bin/clickhouse
9. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000017d41b27 in /usr/bin/clickhouse
10. ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017d3f55c in /usr/bin/clickhouse
11. ? @ 0x00007fd70835a609 in ?
12. __clone @ 0x00007fd70827f133 in ?
```

**Comment by anjakefala** [comment]
Hi @maxim-uvarov!

We recently put love into vdsql, but first to solve your problem:
* vdsql has been moved to the [core VisiData repo](https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql). Please reinstall it from there. There are lots of updates there to fix the problems you are seeing with the clickhouse loader.
* you will need at least Python 3.9. [ibis-framework](https://github.com/ibis-project/ibis), the most important dependency of the project, dropped support for [Python 3.8](https://github.com/ibis-project/ibis/pull/6491).
* The test url is now `clickhouse://play:clickhouse@play.clickhouse.com/?secure=1`

I will update the documentation in https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql accordingly!
