### ISSUE TITLE
Postgres connection not working

### ISSUE THREAD

**Issue by spren9er** [saulpw/vdibis#8]
I tried to connect to a local PostgreSQL database via

```bash
vdsql postgres://localhost:5432/my_db
```

but following error occurred:

```bash
Traceback (most recent call last):
  File "/Users/spren9er/.local/share/virtualenvs/vd-UPn86r9P/bin/vdsql", line 15, in <module>
    main.vd_cli()
  File "/Users/spren9er/.local/share/virtualenvs/vd-UPn86r9P/lib/python3.9/site-packages/visidata/main.py", line 350, in vd_cli
    rc = main_vd()
  File "/Users/spren9er/.local/share/virtualenvs/vd-UPn86r9P/lib/python3.9/site-packages/visidata/main.py", line 241, in main_vd
    vs = vd.openSource(p, create=True, **opts) or vd.fail(f'could not open {p}')
  File "/Users/spren9er/.local/share/virtualenvs/vd-UPn86r9P/lib/python3.9/site-packages/visidata/_open.py", line 95, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
  File "/Users/spren9er/.local/share/virtualenvs/vd-UPn86r9P/lib/python3.9/site-packages/visidata/_open.py", line 50, in openPath
    return openfunc(p, filetype=filetype)
TypeError: open_vdsql() got an unexpected keyword argument 'filetype'
```

Database connection works in principle. Following command is successful without any issues

```
vd postgres://localhost:5432/my_db
```

but this is using `psycopg2` and not `ibis` framework.

**Comment by saulpw** [comment]
Hi @spren9er, thanks for reporting this bug; this should be fixed in the `develop` branch.  It will be in v0.2, which we are planning to release soon.
